# Dashboard #

LogAnalyzer_Dashboard_index:
    path:     /
    defaults: { _controller: LogAnalyzerCoreBundle:Dashboard:index }

# Login #

LogAnalyzer_Login_index:
    path:     /
    defaults: { _controller: LogAnalyzerCoreBundle:Login:index }

LogAnalyzer_Login_signInAPI:
    path:     /login/signInAPI/
    defaults: { _controller: LogAnalyzerCoreBundle:Login:signInAPI }

LogAnalyzer_Login_signOutAPI:
    path:     /login/signOutAPI/
    defaults: { _controller: LogAnalyzerCoreBundle:Login:signOutAPI }

# OrganizationAdministration #

LogAnalyzer_OrganizationAdministration_getUserAPI:
    path:     /organizationAdministration/getUserAPI/
    defaults: { _controller: LogAnalyzerCoreBundle:OrganizationAdministration:getUserAPI }

LogAnalyzer_OrganizationAdministration_createUserAPI:
    path:     /organizationAdministration/createUserAPI/
    defaults: { _controller: LogAnalyzerCoreBundle:OrganizationAdministration:createUserAPI }

LogAnalyzer_OrganizationAdministration_deleteUserAPI:
    path:     /organizationAdministration/deleteUserAPI/
    defaults: { _controller: LogAnalyzerCoreBundle:OrganizationAdministration:deleteUserAPI }

LogAnalyzer_OrganizationAdministration_getRoleAPI:
    path:     /organizationAdministration/getRoleAPI/
    defaults: { _controller: LogAnalyzerCoreBundle:OrganizationAdministration:getRoleAPI }